### ISSUE TITLE
Support for react 18

### ISSUE THREAD

**Issue by orangeX6** [harundogdu/react-tiff#2]
Hey @harundogdu , 
Great work on the lib!!! Can you please add support for react ver. 18 in here ?

**Comment by harundogdu** [comment]
Thank you. I am so glad it was useful. You can use it in React versions 16,17 and 18.

@orangeX6

**Comment by pranav-an** [comment]
Hey @harundogdu , 
Thanks for the response! 
Actually yes, as you said I can use it on 16,17 and 18 but  i think  since in package, peerDependencies is ^16.0.0 and not >= 16, typescript gives me some errors and does not let me build : ( 
  "peerDependencies": {
    "react": "^16.0.0"
  },

**Comment by NatalieDinh** [comment]
@harundogdu

Are there any plans for adding react 18 to the peer dependencies? I'm also running into this issue where I am not able to install due to it requiring React 16.

If not, would you consider making this open source, so we may contribute and fix this issue?

Thank you!

**Comment by AnthonyGress** [comment]
Just submitted a simple PR for react 18 support. One liner nice and simple

**Comment by AnthonyGress** [comment]
> @harundogdu
> 
> Are there any plans for adding react 18 to the peer dependencies? I'm also running into this issue where I am not able to install due to it requiring React 16.
> 
> If not, would you consider making this open source, so we may contribute and fix this issue?
> 
> Thank you!

Until my PR with the small fix is merged, i uploaded my fork with the fix to npm under the name `react-tiff-18` works as expected

**Comment by AnthonyGress** [comment]
> @AnthonyGress  hey dear, any update?

@Christiangsn PR is not merged here. My working fork is live on npm just use 'npm install react-tiff-18'

**Comment by Christiangsn** [comment]
> > @AnthonyGress  hey dear, any update?
> 
> @Christiangsn PR is not merged here. My working fork is live on npm just use `npm install react-tiff-18`

Is there @types support for this lib? is there an issue about this?

**Comment by AnthonyGress** [comment]
> > > @AnthonyGress  hey dear, any update?
> 
> > 
> 
> > @Christiangsn PR is not merged here. My working fork is live on npm just use `npm install react-tiff-18`
> 
> 
> 
> Is there @types support for this lib? is there an issue about?

The creator doesn't have types for it. I'm not maintaining it or anything. Just removed the error on install for newer react versions.

**Comment by NatalieDinh** [comment]
> > > @AnthonyGress  hey dear, any update?
> > 
> > 
> > @Christiangsn PR is not merged here. My working fork is live on npm just use `npm install react-tiff-18`
> 
> Is there @types support for this lib? is there an issue about?

@Christiangsn Hi Christian, it doesn’t seem like this package offers types support. But, you should be able to declare the module in a global.d.ts file and still use it. 

Of course it won’t be optimized for typescript, but at least you’ll be able to utilize this package

**Comment by harundogdu** [comment]
Thanks for your contributions

@AnthonyGress

**Comment by AnthonyGress** [comment]
> Thanks for your contributions
> 
> @AnthonyGress

No problem @harundogdu , thanks for making this package. Don't forget to push this update to npm so the package gets updated.

**Comment by harundogdu** [comment]
@AnthonyGress 

Thank you for the reminder. Can you check it?
