### ISSUE TITLE
Add type="button" to buttons for pagination

### ISSUE THREAD

**Issue by kyohei0423** [harundogdu/react-tiff#4]
Hello @harundogdu ,

When previewing a TIFF file in a form tag and clicking the next button in order to check the next page of the TIFF file, the form was submitted immediately. I think the reason the buttons don't have an attribute, type="button".

May I implement it and make PR?

**Comment by harundogdu** [comment]
@kyohei0423 ofc man. Please do it.

**Comment by kyohei0423** [comment]
@harundogdu 
I create PR for this issue. Would you check and review my PR?
https://github.com/harundogdu/react-tiff/pull/6
